{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-datadog.fullname" . }}
  labels:
    {{- include "envoy-datadog.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
  selector:
    {{- include "envoy-datadog.selectorLabels" . | nindent 4 }}
{{- end }}
